# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glgp_cpp <- function(xy, x_test, gIndices, theta, predIndices, lNum, nugget, leaf_size) {
    .Call(`_twingp_glgp_cpp`, xy, x_test, gIndices, theta, predIndices, lNum, nugget, leaf_size)
}

get_twinIndices <- function(data, r, rv, runs, u1, leaf_size = 8L) {
    .Call(`_twingp_get_twinIndices`, data, r, rv, runs, u1, leaf_size)
}

